///@category Profiles
/*
Returns the number of profiles that are currently in the game, including autogenerated profiles (such as the profiles for CPUs).
*/
function profile_count()
	{
	return array_length(engine().profiles);
	}
/* Copyright 2024 Springroll Games / Yosi */