///@category Profiles
///@param {string} name			The name of the profile you are looking for
/*
Returns the index of a non-automgenerated profile with the given name in the profiles array.
If no such profile exists, -1 is returned.
*/
function profile_find()
	{
	var _name = argument[0];
	for (var i = 0; i < array_length(engine().profiles); i++)
		{
		if (profile_get(i, PROFILE.name) == _name && !profile_get(i, PROFILE.autogenerated))
			{
			return i;
			}
		}
	return -1;
	}
/* Copyright 2024 Springroll Games / Yosi */