function __optimized_load_obj_hitbox_detectbox()
	{
	var _b = argument[0];
	sync_id=buffer_read(_b,buffer_u32);
	owner=buffer_read(_b,buffer_f64);
	player_id=buffer_read(_b,buffer_f64);
	facing=buffer_read(_b,buffer_s8);
	overlay_alpha=buffer_read(_b,buffer_f64);
	has_hit=buffer_read(_b,buffer_bool);
	destroy=buffer_read(_b,buffer_bool);
	overlay_color=buffer_read(_b,buffer_s32);
	overlay_sprite=buffer_read(_b,buffer_s32);
	hitbox_group=buffer_read(_b,buffer_s8);
	overlay_angle=buffer_read(_b,buffer_f64);
	has_been_blocked=buffer_read(_b,buffer_bool);
	detect_script=buffer_read(_b,buffer_s32);
	detect_multihit=buffer_read(_b,buffer_bool);
	overlay_speed=buffer_read(_b,buffer_f64);
	owner_ystart=buffer_read(_b,buffer_s16);
	overlay_scale=buffer_read(_b,buffer_f64);
	overlay_frame=buffer_read(_b,buffer_f64);
	owner_xstart=buffer_read(_b,buffer_s16);
	check_first=buffer_read(_b,buffer_bool);
	overlay_facing=buffer_read(_b,buffer_s8);
	lifetime=buffer_read(_b,buffer_f64);
	can_be_parried=buffer_read(_b,buffer_bool);
	x=buffer_read(_b,buffer_f32);
	y=buffer_read(_b,buffer_f32);
	xstart=buffer_read(_b,buffer_f32);
	ystart=buffer_read(_b,buffer_f32);
	sprite_index=buffer_read(_b,buffer_s32);
	image_index=buffer_read(_b,buffer_f64);
	image_xscale=buffer_read(_b,buffer_f64);
	image_yscale=buffer_read(_b,buffer_f64);
	image_angle=buffer_read(_b,buffer_f64);
	hit_vfx_style=buffer_read_auto(_b);
	hit_sfx=buffer_read_auto(_b);
	hit_restriction=buffer_read(_b,buffer_s8);
	pre_hit_script=buffer_read(_b,buffer_s32);
	post_hit_script=buffer_read(_b,buffer_s32);
	hurtbox_hit_list=buffer_read_list(_b,buffer_f64);
	}
/* Copyright 2024 Springroll Games / Yosi */