function css_ui_clear_button_step()
	{
	ui_button_step();

	if (ui_clicked)
		{
		with (obj_css_ui)
			{
			menu_sound_play(snd_menu_back);
			var _array = css_players_get_array();
			//Delete player UI
			for (var i = 0; i < array_length(_array); i++)
				{
				var _group = css_player_get(_array[@ i], CSS_PLAYER.custom).group;
				ui_group_delete(_group);
				}
			//Delete all players
			css_players_clear();
			//Disconnect controllers
			mis_device_disconnect_all();
			//Delete UI Cursors
			ui_cursor_delete_all();
			//Get rid of autogenerated profiles
			profile_clean_auto();
			//Reset the index
			engine().css_index_current = 0;
			}
		}
	}
/* Copyright 2024 Springroll Games / Yosi */