///@category Palettes
///@param {struct} palette_data			The struct of palette data to get an alpha value from
///@param {int} index					The index (row)
///@param {int} [column]				The column
/*
Returns a single alpha value (0-255) from the given palette data at the specified row and column.
By default, column 0 is chosen.
Palette data structs are generated by the function <palette_colors_get_from_sprite> or <palette_slice>.

Please note: The "palette_data" instance variable of <obj_player> only has a single column, since <palette_slice> is used on it. Due to this, trying to get a color from any column other than 0 will result in an error.
*/
function palette_color_alpha_get()
	{
	var _pal = argument[0];
	var _in = argument[1];
	var _pal_alphas = _pal.alphas;
	var _col = argument_count > 2 ? argument[2] : 0;
	var _colors_per_column = _pal.colors_per_column;
	return _pal_alphas[@ _in + (_col * _colors_per_column)];
	}
/* Copyright 2024 Springroll Games / Yosi */