///@category Profiles
///@param {string} name						The name of the new profile
///@param {struct} custom_controls			The custom controls struct
///@param {bool} auto						Whether the profile is autogenerated or not
///@param {array} [favorite_colors]			An array of favorite colors for every character
/*
Adds a new profile to the engine().<profiles> array with the given values, and returns the index of the profile in the array.
The custom controls struct should be created with <custom_controls_create>.
*/
function profile_create()
	{
	var _new = [];
	_new[@ PROFILE.name] = argument[0];
	_new[@ PROFILE.custom_controls] = argument[1];
	_new[@ PROFILE.autogenerated] = argument[2];
	_new[@ PROFILE.favorite_colors] = argument_count > 3 ? argument[3] : array_create(character_count(), 1);
	array_push(engine().profiles, _new);
	return array_length(engine().profiles) - 1;
	}
/* Copyright 2024 Springroll Games / Yosi */