function __optimized_load_obj_entity()
	{
	var _b = argument[0];
	sync_id=buffer_read(_b,buffer_u32);
	any_hitbox_has_hit=buffer_read(_b,buffer_bool);
	facing=buffer_read(_b,buffer_s8);
	player_color=buffer_read(_b,buffer_s8);
	player_team=buffer_read(_b,buffer_s8);
	owner=buffer_read(_b,buffer_f64);
	player_id=buffer_read(_b,buffer_f64);
	collision_flags=buffer_read(_b,buffer_s32);
	any_hitbox_has_been_blocked=buffer_read(_b,buffer_bool);
	self_hitlag_frame=buffer_read(_b,buffer_f64);
	state=buffer_read(_b,buffer_s32);
	palette_base=buffer_read_array(_b,buffer_f64);
	palette_swap=buffer_read_array(_b,buffer_f64);
	fade_value=buffer_read(_b,buffer_f64);
	hsp=buffer_read(_b,buffer_f64);
	vsp=buffer_read(_b,buffer_f64);
	hsp_frac=buffer_read(_b,buffer_f64);
	vsp_frac=buffer_read(_b,buffer_f64);
	hsp_moved=buffer_read(_b,buffer_f64);
	vsp_moved=buffer_read(_b,buffer_f64);
	damage_attack_multiplier=buffer_read(_b,buffer_f64);
	knockback_multiplier=buffer_read(_b,buffer_f64);
	x=buffer_read(_b,buffer_f32);
	y=buffer_read(_b,buffer_f32);
	xstart=buffer_read(_b,buffer_f32);
	ystart=buffer_read(_b,buffer_f32);
	mask_index=buffer_read(_b,buffer_s32);
	sprite_index=buffer_read(_b,buffer_s32);
	image_index=buffer_read(_b,buffer_f64);
	image_speed=buffer_read(_b,buffer_f64);
	image_xscale=buffer_read(_b,buffer_f64);
	image_yscale=buffer_read(_b,buffer_f64);
	image_angle=buffer_read(_b,buffer_f64);
	image_blend=buffer_read(_b,buffer_s32);
	image_alpha=buffer_read(_b,buffer_f64);
	layer=buffer_read(_b,buffer_s32);
	palette_data=buffer_read_struct(_b);
	hitbox_groups=buffer_read_array(_b);
	custom_entity_struct=buffer_read_struct(_b);
	custom_ids_struct=buffer_read_struct(_b,buffer_f64);
	my_hitboxes=buffer_read_array(_b,buffer_s32);
	}
/* Copyright 2024 Springroll Games / Yosi */